name: rain
description: Weather app.

publish_to: "none"

version: 1.2.0+23

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  dio: ^5.2.1+1
  intl: ^0.18.0
  isar: ^3.1.0+1
  shimmer: ^3.0.0
  iconsax: ^0.0.8
  timezone: ^0.9.2
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  workmanager: ^0.5.1
  home_widget: ^0.3.0
  flutter_glow: ^0.3.0
  url_launcher: ^6.1.11
  dynamic_color: ^1.6.6
  path_provider: ^2.0.15
  flutter_timezone: ^1.0.7
  package_info_plus: ^4.0.2
  connectivity_plus: ^4.0.1
  isar_flutter_libs: ^3.1.0+1
  flutter_displaymode: ^0.6.0
  lat_lng_to_timezone: ^0.2.0
  scrollable_positioned_list: ^0.3.8
  flutter_local_notifications: ^15.0.1
  internet_connection_checker: ^1.0.0+1

# Uncomment this for publishing FLOSS variant
# dependency_overrides:
#   geolocator_android:
#     git:
#       url: https://github.com/Zverik/flutter-geolocator.git
#       ref: floss
#       path: geolocator_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  isar_generator: ^3.1.0+1
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
